version: '3.0'
services:
  rasa:
    image: "rasa/rasa:3.3.0-full"
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run
      - -m 
      - models 
      - --enable-api 
      - --cors 
      - "*" 
      - --debug

  app:
    image: abdulrahman16/firstchatbot:firstcommit
    expose: ["5055","5"]
  
  # flask:
  #   image: abdulrahman16/firstchatbot:flask-chat
  #   expose: ["8001","5000"]